channels:
  - conda-forge
  - sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.9
  - gammapy=1.2
  - ipython=8.7.0
  - cython
  - jupyter
  - jupyterlab=3.5
  - pyyaml=6.0
  - click=8.1.3
  - numpy=1.24
  - scipy=1.10.1
  - pandas=1.5.2
  - matplotlib=3.7
  - astropy=5.3
  - regions=0.7
  - iminuit=2.21
  - sherpa=4.15
  - healpy=1.16
  - naima=0.10
  - pydantic=1.9
  - emcee=3.1.3
  - corner=2.2.1
  - pip
  - requests
  - tqdm
  - ctapipe=0.19.2
  - ctaplot~=0.6.4
  - h5py
  - notebook
  - joblib~=1.2.0
  - toml
  - protobuf=3.20
  - pyparsing
  - scikit-learn=1.2
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - sphinx-argparse
  - sphinxcontrib-mermaid
  - nbsphinx
  - numba
  - numpydoc
  - pymongo
  - seaborn
  - ctapipe_io_lst=0.22
  - pytest
  - pyirf~=0.10.0
